"""init schema — Phase 1

Uses Base.metadata.create_all for simplicity. Subsequent migrations should be
autogenerated with `alembic revision --autogenerate`.

Revision ID: 0001
Revises:
Create Date: 2026-05-19
"""
from alembic import op

from app.database import Base
from app import models  # noqa: F401


revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
